compare:
  image: ubuntu:latest
  tags:
    - docker-build
  stage: compare
  before_script:
    # ...
  script:
    # ...
    - |- 
      for i in {1..1}
      do
        echo "Analyzing video ${i} ..." 
        ALGO_VERSION="current-image:latest" VIDEO=${i} docker compose -f docker-compose.yaml up --no-log-prefix --abort-on-container-exit | grep "group_18" >> current.csv
        ALGO_VERSION="previous-image:latest" VIDEO=${i} docker compose -f docker-compose.yaml up --no-log-prefix --abort-on-container-exit | grep "group_18" >> previous.csv
        echo "Done analyzing video ${i}"
        echo "Current results: "
        cat current.csv
        echo "Previous results: "
        cat previous.csv
      done
